$(function (){
    $("#d1").hover(function(){
        $(this).css("background-color","black");
        $(this).css("color","white");
       });
       $("#d2").hover(function(){
        $(this).css("background-color","black");
        $(this).css("color","white");
       });
       $("#d3").hover(function(){
        $(this).css("background-color","black");
        $(this).css("color","white");
       });
       $("#d4").hover(function(){
        $(this).css("background-color","black");
        $(this).css("color","white");
       });
       $("#d5").hover(function(){
        $(this).css("background-color","black");
        $(this).css("color","white");
       });
       $("#d6").hover(function(){
        $(this).css("background-color","black");
        $(this).css("color","white");
       });
       $("#d7").hover(function(){
        $(this).css("background-color","black");
        $(this).css("color","white");
       });
       $("#d8").hover(function(){
        $(this).css("background-color","black");
        $(this).css("color","white");
       });
});